name: 'Setup and Test'
description: 'Composite action to setup environment and run tests'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: true
    default: '20.x'
  debug:
    description: 'Enable debug logging'
    required: false
    default: false
    type: boolean

runs:
  using: "composite"
  steps:
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Run tests
      run: npm test
      shell: bash